#!/bin/sh

set -e

lb config noauto \
        --archive-areas "main contrib non-free" \
        --image-name "convallaria" \
        --iso-publisher "Convallaria_Dev" \
        --system "live" \
        --architectures "amd64" \
        --mirror-binary "https://mirrors.bfsu.edu.cn/debian" \
        --mirror-binary-security "https://mirrors.bfsu.edu.cn/debian-security" \
        --mirror-bootstrap "https://mirrors.bfsu.edu.cn/debian" \
        --mirror-chroot "https://mirrors.bfsu.edu.cn/debian" \
        --mirror-chroot-security "https://mirrors.bfsu.edu.cn/debian-security" \
        --mirror-debian-installer "https://mirrors.bfsu.edu.cn/debian" \
"${@}"

cp /root/build-res/packages /root/convallaria/config/package-lists/standard.list.chroot

cp /root/build-res/init /root/convallaria/config/hooks/live/Convallaria.hook.chroot